#!/bin/bash

source $(dirname "$0")/common

IMAGE_NAME=${REPO##*/}
if [[ $ENV != production ]]; then
    IMAGE_NAME=$IMAGE_NAME-$ENV
fi
IMAGE_ID=$(tr '[A-Z]' '[a-z]' <<< docker.pkg.github.com/$REPO/$IMAGE_NAME)
echo ::set-env name=IMAGE_ID::$IMAGE_ID

log "Logging in to docker registry..."
echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin

log "Pulling latest $IMAGE_ID from registry..."
docker pull $IMAGE_ID || true

log "Building $IMAGE_ID..."
if [[ "$DOCKERFILE" ]]; then
    cp -r $DOCKERFILE/. .
fi
export DOCKER_BUILDKIT=1
export DOCKER_BUILD_ARG_ENV=$ENV
export DOCKER_BUILD_ARG_BUILDKIT_INLINE_CACHE=1
DOCKER_BUILD_ARGS="$(env | (grep '^DOCKER_BUILD_ARG_' || :) | sed 's/^DOCKER_BUILD_ARG_/--build-arg /')"
docker build . --tag $IMAGE_ID --cache-from $IMAGE_ID $DOCKER_BUILD_ARGS $DOCKERFILE_ARG

log "Successfully built $IMAGE_ID."