#!/bin/bash

source $(dirname "$0")/common

REGISTRY=ghcr.io
REGISTRY_USERNAME=${GITHUB_REPOSITORY%%/*}

IMAGE_NAME=${GITHUB_REPOSITORY#*/}
if [[ $ENV != production ]]; then
    IMAGE_NAME=$IMAGE_NAME-$ENV
fi
IMAGE_ID=$(tr '[A-Z]' '[a-z]' <<< $REGISTRY/$REGISTRY_USERNAME/$IMAGE_NAME)
echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

log "Logging in to docker registry..."
echo "$REGISTRY_TOKEN" | docker login $REGISTRY -u $REGISTRY_USERNAME --password-stdin

log "Building $IMAGE_ID..."
if [[ "$DOCKERFILE" ]]; then
    cp -r $DOCKERFILE/. .
fi
export DOCKER_BUILDKIT=1
export DOCKER_BUILD_ARG_ENV=$ENV
export DOCKER_BUILD_ARG_BUILDKIT_INLINE_CACHE=1
DOCKER_BUILD_ARGS="$(env | (grep '^DOCKER_BUILD_ARG_' || :) | sed 's/^DOCKER_BUILD_ARG_/--build-arg /')"
docker build . --tag $IMAGE_ID --cache-from $IMAGE_ID $DOCKER_BUILD_ARGS $DOCKERFILE_ARG

log "Successfully built $IMAGE_ID."
