#!/bin/bash

source $(dirname "$0")/common

log "Publishing $IMAGE_ID:latest to registry..."
docker push $IMAGE_ID:latest
if [[ $ENV == production ]]; then
    VERSION=$(($(git rev-list --count HEAD) % 9 + 1)) # rotate between versions 1 to 9
    log "Publishing $IMAGE_ID:$VERSION to registry..."
    docker tag $IMAGE_ID:latest $IMAGE_ID:$VERSION
    docker push $IMAGE_ID:$VERSION
 else
    VERSION=latest
 fi
echo ::set-env name=VERSION::$VERSION

log "Successfully published $IMAGE_ID:$VERSION to registry."