name: main

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  GITHUB_USERNAME: simonkotwicz
  GITHUB_TOKEN: ${{ secrets.githubContainerRegistryToken }}

jobs:
  deliver:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: deliver
    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish
        run: |
          echo $GITHUB_TOKEN | docker login $REGISTRY -u $GITHUB_USERNAME --password-stdin

          IMAGE_ID=$REGISTRY/$GITHUB_USERNAME/$IMAGE_NAME
          docker pull $IMAGE_ID || true

          export DOCKER_BUILDKIT=1
          docker build . --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $IMAGE_ID --tag $IMAGE_ID

          docker push $IMAGE_ID