name: main

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  REGISTRY_TOKEN: ${{ secrets.githubContainerRegistryToken }}
  REGISTRY_USERNAME: simonkotwicz

jobs:
  deliver:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: deliver
    steps:
      - uses: actions/checkout@v2
      - name: Build and Publish
        run: |
          echo $REGISTRY_TOKEN | docker login $REGISTRY -u $REGISTRY_USERNAME --password-stdin

          IMAGE_ID=$REGISTRY/$REGISTRY_USERNAME/$IMAGE_NAME

          docker pull $IMAGE_ID
          docker build . --cache-from $IMAGE_ID --tag $IMAGE_ID

          docker push $IMAGE_ID